# Usar Ubuntu 20.04 como base
FROM ubuntu:20.04

# Evitar que se solicite la interacción del usuario durante la construcción de la imagen
ARG DEBIAN_FRONTEND=noninteractive

# Actualizar el sistema e instalar las dependencias necesarias
RUN apt-get update && apt-get install -y \
    python3.8 \
    python3-pip \
    ffmpeg \
    libsm6 \
    libxext6

# Crear un directorio de trabajo
WORKDIR /app

# Copiar el archivo de requerimientos al contenedor
COPY requirements.txt .

# Instalar las dependencias de Python
RUN pip3 install -r requirements.txt

# Copiar el resto de los archivos del proyecto al contenedor
COPY . .

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python3", "app.py"]